// Import the Prisma client that was generated by Prisma.
// This client is used to communicate with your PostgreSQL database.
import { PrismaClient } from "@/generated/prisma/client";
// In Node.js there is a global object that persists across modules.
// We extend its type so we can safely store Prisma on it.
// This prevents TypeScript errors when attaching custom properties.
const globalForPrisma = global as unknown as {
  prisma: PrismaClient;
};
// If Prisma already exists on the global object, reuse it.
// Otherwise create a new PrismaClient instance.
//
// Why?
// In development, frameworks like Next.js reload modules frequently.
// Without this check, a new DB connection would be created every reload,
// eventually exhausting the database connection pool.
const prisma = globalForPrisma.prisma || new PrismaClient();
// Only store the Prisma instance globally in development.
// In production, we avoid polluting the global scope and just create one instance.
if (process.env.NODE_ENV !== "production") {
  globalForPrisma.prisma = prisma;
}
// Export the Prisma instance so it can be used anywhere in the app.
export default prisma;
